# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    contracts:
      - name: BorrowOperations
        address:
          - 0x783c5e5ea9a84350cfced8e217049a9f0ad70b11aaf42fc9ed9fd671bb401f97
        abi_file_path: abis/borrowoperations-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: OpenTroveEvent
            logId: '17081261052530365109'
          - name: CloseTroveEvent
            logId: '2361378587801497692'
          - name: AdjustTroveEvent
            logId: '6739255540342412543'
      - name: StabilityPool
        address:
          - 0xe8b947dc0d738024096c209f87968782ad328ed5e71b71f57d9e4018f9e686c0
        abi_file_path: abis/stabilitypool-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: StabilityPoolLiquidationEvent
            logId: '4532511178510817406'
          - name: ProvideToStabilityPoolEvent
            logId: '11918694519390339650'
          - name: WithdrawFromStabilityPoolEvent
            logId: '9108112476981792364'
      - name: USDM
        address:
          - 0x4d991aecdf1615def5bdb432ab683394787182e5cfad83988b856c8d388e449f
        abi_file_path: abis/usdm-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: TotalSupplyEvent
            logId: '17462098202904023478'
          - name: Mint
          - name: Burn
      - name: TroveManager
        address:
          - 0x22a4c76edce873781e94a33627170656a507e1badf906fabdbdfaa3b5165a38c
          - 0xc944cfeb826b3a62b648fe81e397256cc24364367089febcb40a96bb454f8b70
          - 0x4fa56ee8ec817b31818407ba08c1a20c9d70cf0d245ce644d2ede713a50b4d58
        abi_file_path: abis/trovemanager-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: TrovePartialLiquidationEvent
            logId: '1415805281139303833'
          - name: TroveFullLiquidationEvent
            logId: '3901993240860012357'
          - name: RedemptionEvent
            logId: '13563887075398870426'
